version: "3.1"
services:
    db:
      image: mariadb
      container_name: magento-db
      restart: always
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_USER=user
          - MYSQL_PASSWORD=root
      volumes:
        - ${DB_PATH_HOST}:/var/lib/mysql

    redis:
      image: redis:latest
      container_name: magento-redis
      working_dir: ${APP_PATH_CONTAINER}
      restart: always
      ports:
        - "6380:6379"
      volumes:
        - ${REDIS_PATH_CONF}:/redis.conf
      command: [ "redis-server", "/redis.conf" ]

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      ports:
        - 8081:80
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=db
      depends_on:
        - db

    webserver:
      image: nginx:alpine
      container_name: magento-webserver
      working_dir: ${APP_PATH_CONTAINER}
      volumes:
          - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: magento-php-fpm
      restart: always
      working_dir: ${APP_PATH_CONTAINER}
      volumes:
        - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      ports:
        - "9001:9000"

#    rabbitmq:
#      image: rabbitmq:3.7-management-alpine
#      ports:
#        - "15672:15672"
#        - "5672:5672"
#      volumes:
#        - rabbitmqdata:/var/lib/rabbitmq